### ISSUE TITLE
Incompatibility with towncrier 22.12.0

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/sphinx-changelog#16]
Started seeing the error that @namurphy reported at https://github.com/twisted/towncrier/issues/461 . Something something about "abusing private API" over there.

**Comment by pllim** [comment]
See https://github.com/twisted/towncrier/issues/461#issuecomment-1363261056 for proposed fix.

**Comment by namurphy** [comment]
Thank you for raising this!  I had meant to, but then got distracted by an open source space pirate capitalism adventure exploration magnetohydrodynamic game.

The reason appears to be that the private `Config` object in `towncrier` got changed into a `dataclass`, which then broke things that depended on it.  I wasn't able to find a place where a `Config` object is used directly in `sphinx-changelog` (at least by name), so I'm not sure where the source of the problem is.

**Comment by pllim** [comment]
Who is maintaining this package on the OpenAstronomy side?
